### ISSUE TITLE
Add a built-in web server to make the project self-contained

### ISSUE THREAD

**Issue by wangyz** [wangyz/destinyc#1]
To make it easier to develop it's necessary to add a built-in web server so things can run w/o needing any external dependencies.

It may be done by incorporating a web framework that provides a built-in web server, such as Symfony Framework written in PHP or Django for Python. Should we choose to do so we can also use the recommended directory structure of the chosen framework.

**Comment by wangyz** [comment]
It's probably a good idea to choose Play Framework in Java / Scala. It provides seed templates which can be used for generating new projects.

The detailed instruction for getting started can be found here - https://www.playframework.com/download and the seed template option is the second within the page.

**Comment by liwenjun1988** [comment]
Done
